### ISSUE TITLE
THE  tskn theme is having a lot problems

### ISSUE THREAD

**Issue by drstrangez0** [ethomasv/RemNoteTheme#14]
i think Remnote update there css or something but im having a lot problems such as in searching or auto searching and also i cant link i think the css need updating 😅
And thanks advance .

**Comment by ethomasv** [comment]
You have to provide more details about the issues you're having. I don't have any problems with search or linking, so I can't help you with that unless you explain what kind of problems you're experiencing.

**Comment by drstrangez0** [comment]
the first issue is when ever i want to search for something it will not show anything as shown in the GIF bellow  
![sea](https://user-images.githubusercontent.com/70066742/99384864-20eba980-28e1-11eb-8262-fab11963c3a6.gif)
the second issue is  in the auto searching the text will hiding and i can't link anything  as shown in the 
![ezgif com-crop](https://user-images.githubusercontent.com/70066742/99384954-48db0d00-28e1-11eb-8912-71911c934dd7.gif)
GIF bellow

**Comment by hannesfrank** [comment]
You can try this port to Custom CSS: https://hannesfrank.github.io/remnote-library/#/scroll/com.github.hannesfrank.remnote-library.tskn-theme

I fixed a few of those search box issues (and tried to document it as best as possible in the commit history in case someone wants to port it back to the stylus version).
